CREATE TABLE chatroom (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    description text NOT NULL,
    created TIMESTAMPTZ DEFAULT now() NOT NULL
);

CREATE TABLE person (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    created TIMESTAMPTZ DEFAULT now() NOT NULL
);

CREATE TABLE message (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    content_type text NOT NULL,
    message text NOT NULL,
    content_id text NOT NULL,
    created TIMESTAMPTZ DEFAULT now() NOT NULL,
    chatroom_id INTEGER
        REFERENCES chatroom(id) ON DELETE CASCADE NOT NULL,
    person_id INTEGER
        REFERENCES person(id) ON DELETE CASCADE NOT NULL
);